[package]
name = "open-flight-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.dependencies]
msfs = "0.1.0"
hidapi = "1.3.2"

[features]
default = ["teensy_hid"]
teensy_hid = []